const data = {
    dishes: [
        {
            id: '1',
            name: "Butternut Squash Soup",
            preptime: 0.25,
            cooktime: 1,
            cost: 2,
            category: "Soup",
            image: "./butternut-squash-soup.jpg",
        },
        {
            id: '2',
            name: "Tomato Soup",
            preptime: 0.25,
            cooktime: 0.5,
            cost: 1.50,
            category: "Soup",
            image: "./tomato-soup.jpg",
        },
        {
            id: '3',
            name: "Chicken Noodle Soup",
            preptime: 0.25,
            cooktime: 1,
            cost: 2.50,
            category: "Soup",
            image: "./chicken-soup.jpg",
        },
        {
            id: '4',
            name: "Italian salad",
            preptime: 0.25,
            cooktime: 0.5,
            cost: 0.50,
            category: "Side",
            image: "./italian-salad.jpg",
        },
        {
            id: '5',
            name: "Mashed potatoes",
            preptime: 0.5,
            cooktime: 0.75,
            cost: .50,
            category: "Side",
            image: "./mashed-potatoes.jpg",
        },
        {
            id: '6',
            name: "Mac n Cheese",
            preptime: 0.5,
            cooktime: 1.5,
            cost: 3.00,
            category: "Side",
            image: "./macncheese.jpg",
        },
        {
            id: '7',
            name: "Turkey",
            preptime: 0.75,
            cooktime: 3.5,
            cost: 12,
            category: "Main",
            image: "./turkey.jpg",
        },
        {
            id: '8',
            name: "Ham",
            preptime: 0.25,
            cooktime: 2,
            cost: 8,
            category: "Main",
            image: "./ham.jpg",
        },
        {
            id: '9',
            name: "Tofurky",
            preptime: 0.5,
            cooktime: 1.5,
            cost: 10,
            category: "Main",
            image: "./tofurky.jpg",
        },
        {
            id: '10',
            name: "Apple Pie",
            preptime: 0.5,
            cooktime: 3,
            cost: 8,
            category: "Dessert",
            image: "./apple-pie.png",
        },
        {
            id: '11',
            name: "Pumpkin Pie",
            preptime: 0.5,
            cooktime: 1,
            cost: 9.5,
            category: "Dessert",
            image: "./pumpkin-pie.png",
        },
        {
            id: '12',
            name: "Pumpkin Roll",
            preptime: 0.3,
            cooktime: 2,
            cost: 7.5,
            category: "Dessert",
            image: "./pumpkin-roll.jpg",
        },
    ]
}

export default data;
